#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/ProjectileMotionforChunkers.jar:$APPDIR/lib/ant-launcher.jar:$APPDIR/lib/ant.jar:$APPDIR/lib/core.jar" projectilemotionforchunkers.ProjectileMotionforChunkers
